filter_scenario = [
  "MixedScenario",
  "IterScenario",
  "UnionScenario",
  "IntersectionScenario",
  "DifferenceScenario",
  "SymmetricDifferenceScenario",
]
sample = 20
min_bit = 5
max_bit = 12
filter_implementation = [
  "AsmCustomBitSet",
  "ByteArraySet",
  "SimdBitSet",
  "CustomBitSet",
  "BitTreeSet",
  "LibBitSet",
  "LibBitVec",
  "LibFixedBitSet",
  "LibIdlset",
  "StdHashSet",
  "StdHashSetDefaultFunc",
  "StdHashSetNoHasher",
  "LibRangeSetBlaze",
  "IntervalSet",
  "LibRoaring",
  "LibCRoaring",
  "StdTreeSet",
  "StdTreeSetDefaultFunc",
  "LibFxHashSet",
  "LibFxHashSetDefaultFunc",
  "StdVec",
  "StdVecDicotomie",
  "LibAvlTree",
  "LibRBTree",
  "BinarySearchTree",
  "IntervalResourceSet",
]
